### ISSUE TITLE
Upload throws error after completion 100%

### ISSUE THREAD

**Issue by babs100** [benjreinhart/react-native-aws3#35] opened 2017-03-14 16:52 UTC
I have uploaded twice before and it work well. suddenly
When I upload a file, it throws an error when it is at 100% uploaded:

{"line":14492, "column":65, "sourceURL":"http://localhost:8081/"}

Please any help

**Comment by benjreinhart** [comment] 2017-04-04 22:53
Are you still having issues? I'm going to close this because I haven't seen this myself nor have I seen many others experience this (except when they had issues local to their environment/credentials). Also, that blip of stack trace doesn't help because that's local to your build.

**Closed by benjreinhart** 2017-04-04 22:53 UTC

**Comment by babs100** [comment] 2017-04-04 22:58
Thank you very much. The issue was resolved. Its local

**Comment by parijatsahai** [comment] 2017-07-06 02:25
@babs100 What was the root cause and solution? Could you please elaborate here for everyone?
